[package]
name    = "shlakoblokunos"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]
path       = "src/lib.rs"
test       = false
doctest    = false
bench      = false

[profile.release]
panic = "abort"
lto   = true

[profile.dev]
panic = "abort"